### ISSUE TITLE
not working in esp 32

### ISSUE THREAD

**Issue by shsandeepa** [Seeed-Studio/Accelerometer_ADXL335#7]
not working in esp 32

**Comment by ackPeng** [comment]
@shsandeepa Could you provide more details about your problem? What model of esp32 are you using?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]

**Comment by xu-shawn** [comment]
it seems that for some esp 32 platforms the pin slots `A1`, `A2`, etc are not defined in `Arduino.h`
