### ISSUE TITLE
Initial value of acceleration is 1.22g

### ISSUE THREAD

**Issue by AmirulJ97** [Seeed-Studio/Accelerometer_ADXL335#8]
I try to run the code with my accelerometer ADXL335 and print out the value in LCD. In my observation, the initial value of X-axis acceleration is high which is 1.22g to 1.23g. I thought that maybe the initial voltage of the sensor is high and effect the value of the acceleration in the beginning. Hence I try to delay around 1 second, when the sensor is turned on. But the value still same. Can I ask why? How to solve this problem?

**Comment by ackPeng** [comment]
@AmirulJ97 There may be several reasons for this: 1. The sensor is not calibrated properly 2. The sensor is not placed flat 3. The temperature drift of the sensor
I suggest that you try to place the sensor in different positions to see if certain positions can make the value more normal; in addition, you can use software to do compensation calibration, such as subtracting a fixed error value

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
