### ISSUE TITLE
Arduino IDE Package

### ISSUE THREAD

**Issue by xu-shawn** [Seeed-Studio/Accelerometer_ADXL335#9]
Are there any plans to publish an updated version of this library on Arduino IDE? The version online still contains bugs such as #3 that are already fixed in master

**Comment by Lesords** [comment]
Hello, 

Thank you for pointing out this problem.

I will release a new version today.

**Comment by Lesords** [comment]
The latest version has been released.

It takes a day for the Arduino library manager to take effect.

**Comment by Lesords** [comment]
It looks like the latest version is now available for download in arduino, so I'm going to close this issue.

Feel free to reopen it if you have any other questions!
